#!/bin/sh

HACK_INI=/tmp/hack.ini
/usr/bin/awk -F "=" '
BEGIN {
  printf("#  DO NOT EDIT THIS FILE\n");
  printf("*/30 * * * * /usr/sbin/logrotate /etc/logrotate.conf\n");
  printf("5 * * * * /scripts/remove_old.sh\n");
  printf("10 */6 * * * /scripts/memory_check.sh\n");
  printf("*/5 * * * * /scripts/lighttpd.sh watchdog >> /media/mmc/atomhack.log\n");
  while((getline line < "/media/mmc/crontab") == 1) {
    print line;
  }
}

{
  key = $1;
  gsub(/[ \t]/, "", key);
  val = $2;
  gsub(/^[ \t]*/, "", val);
  ENV[key] = val;
}

/^REBOOT_SCHEDULE *=/ {
  if($2 == "") next;
  gsub(/:/,",", $2);
  printf("%s /scripts/reboot.sh\n", $2);
}

/^TIMELAPSE_SCHEDULE *=/ {
  split($2, schedule, ";");
  for(i in schedule) {
    if(schedule[i] == "") continue;
    gsub(/:/,",", schedule[i]);
    printf("%s %d\n", schedule[i], i);
  }
}

END {
  if(ENV["MONITORING_NETWORK"] != "off" || ENV["MONITORING_REBOOT"] != "off" || ENV["HEALTHCHECK"] == "on") {
    printf("*/2 * * * * /scripts/health_check.sh\n");
  }
  if(ENV["RTSP_VIDEO0"] == "on" || ENV["RTSP_VIDEO1"] == "on" || ENV["RTSP_VIDEO2"] == "on") {
    printf("* * * * * /scripts/rtspserver.sh watchdog >> /media/mmc/atomhack.log\n");
  }
  if(ENV["PERIODICREC_CIFS"] == "on" || ENV["ALARMREC_CIFS"] == "on" || ENV["TIMELAPSE_CIFS"] == "on") {
    printf("*/2 * * * * /atom_patch/system_bin/mount_cifs.sh watchdog >> /media/mmc/atomhack.log\n");
  }
}
' $HACK_INI | crontab -
