#!/bin/sh
#
# sshd        Starts dropbear sshd.
#

# Make sure the dropbear program exists
[ -x /usr/sbin/dropbear ] || exit 0

# Only start when login keys are provided on the sdcard
[ -f /media/mmc/authorized_keys ] || exit 0

# Host keys persist on /configs (sdcard ext2 image)
KEYDIR=/configs/etc/dropbear

gen_keys() {
	mkdir -p $KEYDIR
	[ -f $KEYDIR/dropbear_rsa_host_key ] || /usr/bin/dropbearkey -t rsa -f $KEYDIR/dropbear_rsa_host_key
	[ -f $KEYDIR/dropbear_ed25519_host_key ] || /usr/bin/dropbearkey -t ed25519 -f $KEYDIR/dropbear_ed25519_host_key
}

start() {
	printf "Starting dropbear sshd: "
	umask 077
	# Key generation may take a few seconds on the first boot
	( gen_keys
	  /usr/sbin/dropbear -s -r $KEYDIR/dropbear_rsa_host_key -r $KEYDIR/dropbear_ed25519_host_key
	  touch /var/lock/sshd ) &
	echo "OK"
}
stop() {
	printf "Stopping dropbear sshd: "
	killall dropbear
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
    start
	;;
  stop)
    stop
	;;
  restart|reload)
    restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
