#!/bin/sh
#
# Start webhook for atomcam
#

case "$1" in
  start)
    [ -p /var/run/atomapp ] || mkfifo /var/run/atomapp
    /usr/bin/atomhookd &
    /usr/bin/atomrecpostd &
  ;;
  stop)
    killall atomhookd > /dev/null 2>&1
    killall atomrecpostd > /dev/null 2>&1
  ;;
  restart|reload)
    $0 stop
    $0 start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
