################################################################################
#
# dropbear
#
################################################################################

DROPBEAR_VERSION = 2022.83
DROPBEAR_SITE = https://matt.ucc.asn.au/dropbear/releases
DROPBEAR_SOURCE = dropbear-$(DROPBEAR_VERSION).tar.bz2
DROPBEAR_LICENSE = MIT, BSD-2-Clause, BSD-3-Clause
DROPBEAR_LICENSE_FILES = LICENSE

DROPBEAR_PROGRAMS = dropbear dropbearkey dropbearconvert scp
ifeq ($(BR2_PACKAGE_DROPBEAR_CLIENT),y)
DROPBEAR_PROGRAMS += dbclient
endif

DROPBEAR_MAKE = $(MAKE) MULTI=1 SCPPROGRESS=1 PROGRAMS="$(DROPBEAR_PROGRAMS)"
DROPBEAR_DEPENDENCIES = zlib

DROPBEAR_CONF_OPTS = \
	--disable-lastlog \
	--disable-utmp \
	--disable-utmpx \
	--disable-wtmp \
	--disable-wtmpx \
	--disable-loginfunc \
	--disable-pututline \
	--disable-pututxline

define DROPBEAR_INIT_LOCALOPTIONS
	echo '/* generated by dropbear.mk */' > $(@D)/localoptions.h
endef
DROPBEAR_POST_CONFIGURE_HOOKS += DROPBEAR_INIT_LOCALOPTIONS

ifeq ($(BR2_PACKAGE_DROPBEAR_DISABLE_REVERSEDNS),y)
define DROPBEAR_DISABLE_REVERSE_DNS
	echo '#define DO_HOST_LOOKUP 0' >> $(@D)/localoptions.h
endef
DROPBEAR_POST_CONFIGURE_HOOKS += DROPBEAR_DISABLE_REVERSE_DNS
endif

ifeq ($(BR2_PACKAGE_DROPBEAR_SMALL),y)
define DROPBEAR_ENABLE_SMALL_CODE
	echo '#define DROPBEAR_SMALL_CODE 1' >> $(@D)/localoptions.h
endef
DROPBEAR_POST_CONFIGURE_HOOKS += DROPBEAR_ENABLE_SMALL_CODE
endif

define DROPBEAR_INSTALL_TARGET_CMDS
	$(INSTALL) -m 0755 -D $(@D)/dropbearmulti $(TARGET_DIR)/usr/sbin/dropbear
	ln -snf ../sbin/dropbear $(TARGET_DIR)/usr/bin/dropbearkey
	ln -snf ../sbin/dropbear $(TARGET_DIR)/usr/bin/dropbearconvert
	ln -snf ../sbin/dropbear $(TARGET_DIR)/usr/bin/scp
endef

ifeq ($(BR2_PACKAGE_DROPBEAR_CLIENT),y)
define DROPBEAR_INSTALL_CLIENT_SYMLINKS
	ln -snf ../sbin/dropbear $(TARGET_DIR)/usr/bin/dbclient
	ln -snf ../sbin/dropbear $(TARGET_DIR)/usr/bin/ssh
endef
DROPBEAR_POST_INSTALL_TARGET_HOOKS += DROPBEAR_INSTALL_CLIENT_SYMLINKS
endif

$(eval $(autotools-package))
